### ISSUE TITLE
Fix SU101000 (Preferences) - Survey Integration Contact Field selector

### ISSUE THREAD

**Issue by ste-bel** [Acumatica/Acumatica-Surveys#58]
Second tab in the setup screen.
Grid for selecting entities needs a special selector to list contacts related to selected entity.

**Comment by YuriyZaletskyy** [comment]
Hi @ste-bel , I've pushed my changes to your branch, please review and confirm futher.

**Comment by ste-bel** [comment]
Seems to work now.
