### ISSUE TITLE
Header Auto-Adjustment needed for the first Page of the Survey (HTML)

### ISSUE THREAD

**Issue by MvF-Evangelista** [Acumatica/Acumatica-Surveys#71]
I created a test 1-page survey and the "Header" or Title for the page crowds out the first question of the survey when it wraps.  Also, you can see we have some minor alignment issues with the questions not all aligning properly in the left margin.

See attached Screenshot...

![HeaderCrowding](https://user-images.githubusercontent.com/20306239/125708587-bbc311fa-0dde-4587-97ef-8eeb3bae2b4e.PNG)

**Comment by markoan** [comment]
Fixed by switching the WELCOME component for a new HEADER component.
