### ISSUE TITLE
Surveys Locked:  Can't move questions around or add new ones.

### ISSUE THREAD

**Issue by MvF-Evangelista** [Acumatica/Acumatica-Surveys#72]
It appears that each of the surveys that Harsha and I created are "locked" - we can't add new questions, delete questions, or move them around.  I checked to make sure there were no collectors in place causing the "lock".  Please check both SV000005 and SV000006.

![Survey Locked SS01](https://user-images.githubusercontent.com/20306239/125838965-38153b73-1246-4279-b2a2-f900f15756ff.PNG)

**Comment by ste-bel** [comment]
Done.
