### ISSUE TITLE
Required Question (s) doesn't work - page advances without answered.

### ISSUE THREAD

**Issue by MvF-Evangelista** [Acumatica/Acumatica-Surveys#73]
After setting the required question option for any given question, the Survey allows you to advance without answering the required question.

![SS02 - Survey page Advances without Data](https://user-images.githubusercontent.com/20306239/125839975-51de6539-c34c-4fb2-94d7-1db14690bfbc.PNG)
![Survey page Advances without Data](https://user-images.githubusercontent.com/20306239/125839979-dc3015a7-dbba-46df-ac23-0802fa8e01e6.PNG)

**Comment by ste-bel** [comment]
Marco, this is an html issue I believe, could you check if the input required attribute is setup properly?

**Comment by markoan** [comment]
On it

**Comment by markoan** [comment]
Fixed component templates to correctly control required inputs.
