### ISSUE TITLE
When processing Surveys, it fails.

### ISSUE THREAD

**Issue by MvF-Evangelista** [Acumatica/Acumatica-Surveys#78]
In processing the Mark's Most Excellent Survey (SV000005), I get an error.  I tried it for all the unprocessed collectors.
![ss01-Process Survey Errors](https://user-images.githubusercontent.com/20306239/125895183-71bb3379-9de0-4447-b338-dada556d22c9.PNG)
![ss02-Process Survey Errors](https://user-images.githubusercontent.com/20306239/125895281-52db9e2a-a8d3-4c71-ae97-93fb291e3239.PNG)

**Comment by ste-bel** [comment]
Cannot replicate, please do and save the stack trace here.

**Comment by ste-bel** [comment]
Fixed
