### ISSUE TITLE
Generate HTML throws an error

### ISSUE THREAD

**Issue by CloudERP2020** [Acumatica/Acumatica-Surveys#81]
Not knowing I clicked this button "Generate HTML" it throws an error, can you please let me know what this button does and when this button needs to be clicked, and if clicked then this error needs to be caught and appropriate msg needs to be shown.

Trace below ...
<html>
<body>

Unsupported file type. Supported types are: .als, .cer, .csv, .dat, .doc, .docx, .epl, .exe, .gif, .ico, .ics, .jpeg, .jpg, .js, .mdb, .msi, .ofx, .pdf, .pfx, .ppt, .pptx, .qbo, .qfx, .rar, .rtf, .sql, .swf, .txt, .xls, .xlsx, .xml, .zip, .zpl, .pbix, .png, .svg, .tif, .tiff | Send
-- | --
  | Raised At: 7/16/2021 1:38:46 PM | Screen: SU.20.10.00 | Command: GenerateSample |  
Details:7/16/2021 1:38:46 PM Error:Unsupported file type. Supported types are: .als, .cer, .csv, .dat, .doc, .docx, .epl, .exe, .gif, .ico, .ics, .jpeg, .jpg, .js, .mdb, .msi, .ofx, .pdf, .pfx, .ppt, .pptx, .qbo, .qfx, .rar, .rtf, .sql, .swf, .txt, .xls, .xlsx, .xml, .zip, .zpl, .pbix, .png, .svg, .tif, .tiff   at PX.SM.UploadFileMaintenance.SaveFile(FileInfo finfo, FileExistsAction actionOnExisting)   at PX.Survey.Ext.SurveyMaint.SaveContentToAttachment(String name, String content)   at PX.Survey.Ext.SurveyMaint.DoGenerateSample(Survey survey)   at PX.Survey.Ext.SurveyMaint.GenerateSample(PXAdapter adapter)   at PX.Data.PXAction`1.a(PXAdapter A_0)   at PX.Data.PXAction`1.d__28.MoveNext()   at PX.Data.PXAction`1.d__28.MoveNext()   at PX.Web.UI.PXBaseDataSource.tryExecutePendingCommand(String viewName, String[] sortcolumns, Boolean[] descendings, Object[] searches, Object[] parameters, PXFilterRow[] filters, DataSourceSelectArguments arguments, Boolean& closeWindowRequired, Int32& adapterStartRow, Int32& adapterTotalRows)   at PX.Web.UI.PXBaseDataSource.ExecuteSelect(String viewName, DataSourceSelectArguments arguments, PXDSSelectArguments pxarguments)

</body>
</html>

**Comment by ste-bel** [comment]
We need to insert .html in File Upload Preferences
