### ISSUE TITLE
Required field is applied to all questions

### ISSUE THREAD

**Issue by CloudERP2020** [Acumatica/Acumatica-Surveys#82]
All questions are showing as required with * next to it, only fields which are marked as required needs to be shown/validated. This can be seen on Mark's survey and my survey the second question is not mandatory field.

**Comment by ste-bel** [comment]
This is an html thing, all questions come with a * next to it.  Marco can fix that.

**Comment by markoan** [comment]
Fixed component templates. Working correctly now.
