### ISSUE TITLE
Processing Emails - wrong email going out/pending

### ISSUE THREAD

**Issue by MvF-Evangelista** [Acumatica/Acumatica-Surveys#83]
After processing my survey (SV000005), at 9:48am the only email recipient is aarmstorng@altaace.com.  It's not processing the other email recipients... This email is NOT a recipient... see screenshots below.
![ss01- processing email - only aarmstrong](https://user-images.githubusercontent.com/20306239/125983250-f29a8a53-d5e4-4006-93db-6ea1492d7f4b.PNG)
![ss02- processing email - only aarmstrong](https://user-images.githubusercontent.com/20306239/125983253-843d9849-f6ef-45a2-9b1d-b5276b4f577d.PNG)
![ss03- processing email - only aarmstrong](https://user-images.githubusercontent.com/20306239/125983255-342ff949-61c5-4fbc-8118-d61741baa44c.PNG)
![ss04- processing email - only aarmstrong](https://user-images.githubusercontent.com/20306239/125983256-6c329227-13f5-4440-94e1-19eb2dd844a6.PNG)

**Comment by markoan** [comment]
Need to check SurveyCollectorMain.SendMailNotification
Review Notification has correct RefNoteID value to set email fields.

**Comment by ste-bel** [comment]
Works.  Tested by Stéphane and Marco.
