### ISSUE TITLE
Case Entity Not Working when we request survey - HIGH

### ISSUE THREAD

**Issue by CloudERP2020** [Acumatica/Acumatica-Surveys#86]
Hi, 

So here is the flow we want to demonstrate, let us know what's working and what's not there as a feature yet.

We create a Survey for entity CASES and I have changed Mark's survey to be Case entity and also in the preference changed it to his Survey ID.  https://try.acumatica.com/cews3/Main?ScreenId=SU201000&SurveyID=SV000005

We create a case and assign to Business Account and this account contact has a proper email id https://try.acumatica.com/cews3/(W(14))/Main?ScreenId=CR306000&CaseCD=000158 in this case for testing I have added my email address. 

Now I tried to click Request Survey, and nothing happened. Checked the email service no email, so I closed the case and then clicked still nothing happened.

Ideally there should be a mechanism to send Survey to case contact once the case is closed. Or once the user clicks the Request Survey button (for Summit demo this works we are ok).

so please let us know what works and what needs to be fixed.

**Comment by markoan** [comment]
This is just missing configuration:
We need to setup an email account for sending emails, and the business event that triggers email notification using the correct template when there are new collectors assigned to a contact with an email. I will start working on this.

**Comment by markoan** [comment]
This is just missing configuration:
We need to setup an email account for sending emails, and teh business event that triggers email notification using the correct template when there are new collectors assigned to a contact with an email.

**Comment by markoan** [comment]
Solved
