### ISSUE TITLE
Current package conflicts with a preexisting GI

### ISSUE THREAD

**Issue by RobertWaiteREPAY** [Acumatica/Acumatica-Surveys#87]
The attached image shows the error. The likely solution will be to find a different code for the GI.

![image](https://user-images.githubusercontent.com/65043361/127569552-adec6e7d-90bb-4793-9aab-906303d3c66a.png)

**Comment by YuriyZaletskyy** [comment]
Had the same error during development, and on my dev machine just removed
conflicting GI.
But it seems like we need to modify our package.

**Comment by ste-bel** [comment]
We should rename all of our GIs so they are called GISUxxxx or SUxxxxxx

**Comment by MvF-Evangelista** [comment]
Yes, I think we should rename them all as well.  I prefer SUGIxxxxxx.

**Comment by RobertWaiteREPAY** [comment]
I don’t know if SUGIXXXXX will work as I assume a generic inquiry must start with GI as a convention



​Thanks,
Acumatica MVP Developer
APS Payments
Telephone:309.779.9212
Customer Service: 
888.685.1900
***@***.***
Web:www.apspayments.com
From FORTUNE. ©2021 FORTUNE Media IP Limited. All rights reserved. Used under license.
​​
​This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.
​

**Comment by MvF-Evangelista** [comment]
If that's the case, then SUGI...

**Comment by ste-bel** [comment]
Renamed to SUxxxxx.
